### ISSUE TITLE
Potential integer overflow causes runtime panic

### ISSUE THREAD

**Issue by lizhuohua** [magiclen/qrcode-generator#2]
In function `to_image_from_str`, it is possible to construct malformed input and trigger an integer overflow when calculating the length in function `to_image_inner`:

```rust
// Line 445 in lib.rs
let length = size * size;
```

This would result in a smaller buffer being allocated. Accessing this buffer would cause runtime panics.

```rust
// Line 447 in lib.rs
let mut img_raw: Vec<u8> = vec![255u8; length];
```

Example code that triggers the problem:

```rust
use qrcode_generator::to_image_from_str;
use qrcode_generator::QrCodeEcc;

fn main() {
    to_image_from_str("hello", QrCodeEcc::Low, std::usize::MAX);
}
```

**Comment by magiclen** [comment]
It has been fixed. Thank you.

00399d3e3df2c2519b542f9a48a2de3a042c5923
