### ISSUE TITLE
Does not compile for `no_std` projects

### ISSUE THREAD

**Issue by eflukx** [magiclen/qrcode-generator#4]
After setting `default-features = false` in `cargo.toml` this crate does not compile on `no_std` environments as it has some dependencies (on `qrcodegen`) depending on `std`.

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not support the standard library
  = note: `std` is required by `qrcodegen` because it does not declare `#![no_std]`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `qrcodegen` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not support the standard library
  = note: `std` is required by `html_escape` because it does not declare `#![no_std]`

error: build failed
```

**Comment by magiclen** [comment]
You are right. This crate cannot be compiled on `no_std`. I have made this crate removed from the `no-std` category.

**Comment by eflukx** [comment]
Hmm.. pity. I was hoping to include a QR-code generator in my embedded project. As this project supposedly (?) did support `no_std` builds at one time in history, what would it take to make this supported again?
