### ISSUE TITLE
Bloated dependency list

### ISSUE THREAD

**Issue by SirVer** [magiclen/qrcode-generator#5]
Great crate! Thanks for the work.

I'd like to use the image dependency, however it pulls in the full image crate, including encoding and decoding of all image types. Especially JPEG pulls in rayon, which pulls in crossbeam - blowing the dependency list very high.

It would be cool to have the image feature list represented, so I could only select the image types I care about (in our case `png`). For the moment, I will use the crate without image support and instead copy & paste the code that converts from matrix to ImageBuffer into my own code.

**Comment by magiclen** [comment]
Thanks for your suggestions. I've made a small change to not compile the full image crate.
