### ISSUE TITLE
SVG produced are not properly rendered in some apps

### ISSUE THREAD

**Issue by Sky-NiniKo** [magiclen/qrcode-generator#6]
Here is the code I used to generate the svg :
```rust
use qrcode_generator::QrCodeEcc;

fn main() {
    qrcode_generator::to_svg_to_file("Hello world!", QrCodeEcc::Low, 1024, None::<&str>, "svg_output.svg").unwrap();
}
```

## The issue in image (Firefox)
| 100 % | 90 % |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/61370893/230046821-f728cf8f-1873-4df4-8fc9-4e0608a37e25.png) | ![image](https://user-images.githubusercontent.com/61370893/230046709-77834eab-0d77-4bbd-9233-4922c5a678d9.png) | 

## The issue in text form
Some applications, such as Firefox, do not render the svg properly when it is not at its original size (if the svg is zoomed in/out). There are white spaces between the black squares.

## Apps that I tested:
| App | Render properly? |
|--------|--------|
| Firefox | No |
| Chromium browsers | Yes |
| Inkscape | No |
| GIMP | Yes | 

## Possible solution
I am not a svg specialist so don't take my words quite literally.
1.  Enlarging the squares should fix the problem but I don't know if this is the way to go
2. Render svg like [qrcode](https://crates.io/crates/qrcode) (it doesn't have this problem), it uses [`path`](https://github.com/kennytm/qrcode-rust/blob/master/src/render/svg.rs#LL53C24-L53C41) instead of multiple `rect` (this also makes the svg smaller to store)

**Comment by magiclen** [comment]
Good catch! I think we need to use `path` as well. Let me do some research to see how it works.

**Comment by magiclen** [comment]
It should be fixed now. fb5bccd359c4d871175b1ef4735691deed5fd9ac
